plugins {
    id 'java'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.137'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
if (project.hasProperty('mod_version')) {
    base.archivesName = "$mod_id-$mod_version-$minecraft_version"
} else {
    base.archivesName = "$mod_id-$minecraft_version-debug"
}

repositories {
    mavenLocal()
    mavenCentral()
}

neoForge {
    version = neo_version

    parchment {
        mappingsVersion = parchment_mappingsVersion
        minecraftVersion = parchment_minecraftVersion
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    var coremodProject = stonecutter.node.sibling("coremods")

    if (stonecutter.eval(stonecutter.current.version, ">=1.21.4")) {
        jarJar('org.antlr:antlr4-runtime:4.13.2')
    }

    implementation(jarJar(project(coremodProject.getPath())))
    implementation(jarJar(group: 'yuuria.stackupper', name: "StackUpperConfigLibrary", version: '[1,)'))
}


tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : "0.0.0-debug",
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    if (project.hasProperty("mod_version")) {
        replaceProperties.put("mod_version", "$mod_version")
    }
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}