plugins {
    id 'java'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.137'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
if (project.hasProperty('mod_version')) {
    base.archivesName = "$mod_id-$mod_version-$minecraft_version"
} else {
    base.archivesName = "$mod_id-debug-$minecraft_version"
}

repositories {
    mavenLocal()
    mavenCentral()
}

neoForge {
    version = neo_version

    parchment {
        mappingsVersion = parchment_mappingsVersion
        minecraftVersion = parchment_minecraftVersion
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    var coremodProject = stonecutter.node.sibling("coremods")

    if (stonecutter.eval(stonecutter.current.version, ">=1.21.4")) {
        jarJar('org.antlr:antlr4-runtime:4.13.2')
    }

    if (stonecutter.eval(stonecutter.current.version, ">=1.21.10")) {
        implementation(jarJar(project(":coremods:1.21.10")))
    } else {
        implementation(jarJar(project(":coremods:1.21")))
    }

    implementation(jarJar(group: 'yuuria.stackupper', name: "StackUpperConfigLibrary", version: '[1,)'))
}

publishMods {
    if (!rootProject.hasProperty("mod_version")) {
        System.out.println("Can't run publishMods, mod_version property is missing!")
        return
    }
    file = jar.archiveFile
    type = "STABLE"
    changelog = rootProject.file("CHANGELOG.md").getText()
    version = mod_version
    displayName = "StackUpper ${mc_title}-${mod_version}"
    modLoaders.add("neoforge")

    dryRun = providers.environmentVariable("CURSEFORGE_TOKEN").getOrNull() == null
        || providers.environmentVariable("MODRINTH_TOKEN").getOrNull() == null

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        projectId = curseforge_projectId
        minecraftVersions.addAll(property("mc_targets").toString().split(' '))
        clientRequired = true
        serverRequired = true
        changelogType = "markdown"
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = modrinth_projectId
        minecraftVersions.addAll(property("mc_targets").toString().split(' '))
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : "0.0.0-debug",
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    if (project.hasProperty("mod_version")) {
        replaceProperties.put("mod_version", "$mod_version")
    }
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}