mod.id = stackupper
mod.name = StackUpper
mod.license=GPL-3.0
mod.authors=YuuriaSakura
mod.description=Patches Minecraft's max item stack size to allow up to 2.1 billion.
mod.issue_url=https://github.com/MaiKokain/StackUpper/issues
mod.homepage_url=https://github.com/MaiKokain/StackUpper
mod.version=0.0.0