name: Build StackUpper
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build StackUpper
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
      - name: Clone config library
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'MaiKokain'
          repository: 'StackUpperConfigLib'
      - name: Build and publish config library
        working-directory: 'StackUpperConfigLib'
        run: ./gradlew buildAndPublishToMavenLocal
      - name: Delete StackUpperConfigLib folder
        run: rm -rf StackUpperConfigLib
      - name: Build StackUpper
        run: ./gradlew chiseledBuild
      - name: Upload build folder (lazy ass)
        uses: actions/upload-artifact@v4
        with:
          name: 'build'
          path: build